services:
  - type: web
    name: life-control
    runtime: node
    plan: free
    buildCommand: pnpm install --prod=false && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
