const components = {
  "AppShell": "AppComponents",
  "DashboardSection": "sections",
  "PlannerSection": "sections",
  "FinancesSection": "sections",
  "ShoppingSection": "sections",
  "ThemeSelector": "atoms",
  "TaskCard": "atoms",
  "CapacityRing": "atoms",
  "TimeBlock": "atoms",
  "Fab": "atoms",
  "BlockForm": "forms",
  "Sidebar": "shell",
  "ModalShell": "shell",
  "DomainForm": "forms",
  "TaskForm": "forms",
  "FinanceForm": "forms",
  "WalletForm": "forms",
  "PendingTasksPanel": "forms",
  "ShoppingForm": "forms",
  "DomainsSection": "sections",
  "SettingsSection": "sections",
  "Button": "Visual",
  "Link": "Visual",
  "Loading": "Visual",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "Route": "Visual",
  "StorageService": "Service",
  "DomainService": "Service",
  "TaskService": "Service",
  "ExchangeRateService": "Service",
  "TimeBlockService": "Service",
  "FinanceService": "Service",
  "ShoppingService": "Service",
  "ProfileService": "Service"
};

export default components;
